// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCE:
 *     schema.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

func writeArrayUnionFooBar(r []*UnionFooBar, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeUnionFooBar(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayUnionFooBarWrapper struct {
	Target *[]*UnionFooBar
}

func (_ *ArrayUnionFooBarWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ *ArrayUnionFooBarWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ *ArrayUnionFooBarWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ *ArrayUnionFooBarWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ *ArrayUnionFooBarWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ *ArrayUnionFooBarWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ *ArrayUnionFooBarWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ *ArrayUnionFooBarWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ *ArrayUnionFooBarWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ *ArrayUnionFooBarWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *ArrayUnionFooBarWrapper) Finalize()                        {}
func (_ *ArrayUnionFooBarWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r *ArrayUnionFooBarWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r *ArrayUnionFooBarWrapper) AppendArray() types.Field {
	var v *UnionFooBar
	v = NewUnionFooBar()

	*r.Target = append(*r.Target, v)

	return (*r.Target)[len(*r.Target)-1]
}
