// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCE:
 *     schema.avsc
 */
package avro

import (
	"github.com/actgardner/gogen-avro/v7/compiler"
	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
	"io"
)

type Bar struct {
	Id string `json:"id"`
}

const BarAvroCRC64Fingerprint = "\xccv\x16\xcd\xf3v\xa9\xcf"

func NewBar() *Bar {
	return &Bar{}
}

func DeserializeBar(r io.Reader) (*Bar, error) {
	t := NewBar()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err
	}
	return t, err
}

func DeserializeBarFromSchema(r io.Reader, schema string) (*Bar, error) {
	t := NewBar()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err
	}
	return t, err
}

func writeBar(r *Bar, w io.Writer) error {
	var err error
	err = vm.WriteString(r.Id, w)
	if err != nil {
		return err
	}
	return err
}

func (r *Bar) Serialize(w io.Writer) error {
	return writeBar(r, w)
}

func (r *Bar) Schema() string {
	return "{\"fields\":[{\"name\":\"id\",\"type\":\"string\"}],\"name\":\"bar\",\"type\":\"record\"}"
}

func (r *Bar) SchemaName() string {
	return "bar"
}

func (_ *Bar) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ *Bar) SetInt(v int32)       { panic("Unsupported operation") }
func (_ *Bar) SetLong(v int64)      { panic("Unsupported operation") }
func (_ *Bar) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ *Bar) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ *Bar) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ *Bar) SetString(v string)   { panic("Unsupported operation") }
func (_ *Bar) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *Bar) Get(i int) types.Field {
	switch i {
	case 0:
		return &types.String{Target: &r.Id}
	}
	panic("Unknown field index")
}

func (r *Bar) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *Bar) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ *Bar) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Bar) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *Bar) Finalize()                        {}

func (_ *Bar) AvroCRC64Fingerprint() []byte {
	return []byte(BarAvroCRC64Fingerprint)
}
