// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCE:
 *     schema.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v7/compiler"
	"github.com/actgardner/gogen-avro/v7/container"
	"github.com/actgardner/gogen-avro/v7/vm"
)

func NewFooWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewFoo()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type FooReader struct {
	r io.Reader
	p *vm.Program
}

func NewFooReader(r io.Reader) (*FooReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewFoo()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &FooReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r FooReader) Read() (*Foo, error) {
	t := NewFoo()
	err := vm.Eval(r.r, r.p, t)
	return t, err
}
